# Generated by Django 6.1.1 on 2026-09-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='calendar_timezone',
            field=models.CharField(default='UTC', editable=False, max_length=64),
        ),
    ]
