# Generated by Django 6.1.1 on 2026-09-13 11:57

import django.db.models.deletion
from django.db import migrations, models


def backfill_conversions(apps, schema_editor):
    JobPosting = apps.get_model("postings", "JobPosting")
    Conversion = apps.get_model("postings", "PostingApplicationConversion")
    alias = schema_editor.connection.alias
    for job in JobPosting.objects.using(alias).exclude(applied_application_id=None).select_related("applied_application").iterator():
        if job.workspace_id != job.applied_application.workspace_id:
            raise ValueError("Cannot backfill a cross-workspace posting/application link.")
        Conversion.objects.using(alias).get_or_create(
            posting_id=job.pk, application_id=job.applied_application_id,
            defaults={"workspace_id": job.workspace_id,
                      "application_portable_id": job.applied_application.portable_id},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0002_application_portable_identity'),
        ('core', '0003_applicationrequestintent'),
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingApplicationConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_portable_id', models.UUIDField()),
                ('converted_at', models.DateTimeField(null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posting_conversions', to='applications.application')),
                ('posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='postings.jobposting')),
                ('request_intent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.applicationrequestintent')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('posting', 'application'), name='unique_surviving_posting_attempt')],
            },
        ),
        migrations.RunPython(backfill_conversions),
        migrations.RemoveField(
            model_name='jobposting',
            name='applied_application',
        ),
    ]
