# Generated by Django 6.1.1 on 2026-09-28 01:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_jobposting_portable_identity'),
        ('email_sync', '0006_retained_email_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetainedPostingExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(editable=False)),
                ('extractor_method', models.CharField(max_length=64)),
                ('extractor_version', models.CharField(max_length=32)),
                ('snapshot_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('input_spec', models.JSONField()),
                ('payload_digest', models.CharField(editable=False, max_length=64)),
                ('extracted_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('retained_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting_extractions', to='email_sync.retainedmessage')),
            ],
        ),
        migrations.CreateModel(
            name='RetainedPostingExtractionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portable_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('position', models.PositiveIntegerField()),
                ('fields', models.JSONField()),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outputs', to='postings.retainedpostingextraction')),
            ],
        ),
        migrations.AddConstraint(
            model_name='retainedpostingextraction',
            constraint=models.UniqueConstraint(fields=('retained_message', 'operation_id'), name='posting_extraction_operation'),
        ),
        migrations.AddConstraint(
            model_name='retainedpostingextractionoutput',
            constraint=models.UniqueConstraint(fields=('extraction', 'portable_id'), name='posting_output_portable'),
        ),
        migrations.AddConstraint(
            model_name='retainedpostingextractionoutput',
            constraint=models.UniqueConstraint(fields=('extraction', 'position'), name='posting_output_position'),
        ),
    ]
