# Generated by Django 6.1.1 on 2026-09-29 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0007_posting_source_initial_mapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingSourceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(editable=False)),
                ('revision', models.PositiveBigIntegerField()),
                ('mode', models.CharField(choices=[('associate', 'Associate'), ('withdraw', 'Withdraw')], max_length=16)),
                ('method', models.CharField(default='explicit_owner', editable=False, max_length=32)),
                ('decision_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting_source_corrections', to=settings.AUTH_USER_MODEL)),
                ('initial_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='postings.postingsource')),
                ('target_posting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_corrections', to='postings.jobposting')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('initial_source', 'operation_id'), name='posting_source_corr_operation'), models.UniqueConstraint(fields=('initial_source', 'revision'), name='posting_source_corr_revision'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='posting_source_corr_positive'), models.CheckConstraint(condition=models.Q(models.Q(('mode', 'associate'), ('target_posting__isnull', False)), models.Q(('mode', 'withdraw'), ('target_posting__isnull', True)), _connector='OR'), name='posting_source_corr_target'), models.CheckConstraint(condition=models.Q(('method', 'explicit_owner')), name='posting_source_corr_method'), models.CheckConstraint(condition=models.Q(('decision_version', 1)), name='posting_source_corr_version')],
            },
        ),
    ]
