# Generated by Django 6.1.1 on 2026-09-29 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0008_posting_source_corrections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetainedPostingInterpretationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(editable=False)),
                ('revision', models.PositiveBigIntegerField()),
                ('mode', models.CharField(choices=[('select', 'Select'), ('withdraw', 'Withdraw')], max_length=16)),
                ('membership_revision', models.PositiveBigIntegerField(null=True)),
                ('method', models.CharField(default='explicit_owner', editable=False, max_length=32)),
                ('decision_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting_interpretation_decisions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interpretation_decisions', to='postings.retainedpostingitem')),
                ('selected_association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interpretation_decisions', to='postings.retainedpostingitemassociation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'operation_id'), name='posting_interp_operation'), models.UniqueConstraint(fields=('item', 'revision'), name='posting_interp_revision'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='posting_interp_positive'), models.CheckConstraint(condition=models.Q(models.Q(('membership_revision__gte', 0), ('membership_revision__isnull', False), ('mode', 'select'), ('selected_association__isnull', False)), models.Q(('membership_revision__isnull', True), ('mode', 'withdraw'), ('selected_association__isnull', True)), _connector='OR'), name='posting_interp_selection'), models.CheckConstraint(condition=models.Q(('method', 'explicit_owner')), name='posting_interp_method'), models.CheckConstraint(condition=models.Q(('decision_version', 1)), name='posting_interp_version')],
            },
        ),
    ]
