# Generated by Django 6.1.1 on 2026-09-29 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0009_retained_posting_interpretation_decisions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingInterpretationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(editable=False)),
                ('revision', models.PositiveBigIntegerField()),
                ('mode', models.CharField(choices=[('select', 'Select'), ('withdraw', 'Withdraw')], max_length=16)),
                ('mapping_revision', models.PositiveBigIntegerField(null=True)),
                ('method', models.CharField(default='explicit_owner', editable=False, max_length=32)),
                ('decision_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_posting_interpretation_decisions', to=settings.AUTH_USER_MODEL)),
                ('initial_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interpretation_decisions', to='postings.postingsource')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interpretation_decisions', to='postings.jobposting')),
                ('selected_interpretation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posting_decisions', to='postings.retainedpostinginterpretationdecision')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('posting', 'operation_id'), name='job_post_interp_operation'), models.UniqueConstraint(fields=('posting', 'revision'), name='job_post_interp_revision'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='job_post_interp_positive'), models.CheckConstraint(condition=models.Q(models.Q(('initial_source__isnull', False), ('mapping_revision__gte', 0), ('mapping_revision__isnull', False), ('mode', 'select'), ('selected_interpretation__isnull', False)), models.Q(('initial_source__isnull', True), ('mapping_revision__isnull', True), ('mode', 'withdraw'), ('selected_interpretation__isnull', True)), _connector='OR'), name='job_post_interp_selection'), models.CheckConstraint(condition=models.Q(('method', 'explicit_owner')), name='job_post_interp_method'), models.CheckConstraint(condition=models.Q(('decision_version', 1)), name='job_post_interp_version')],
            },
        ),
    ]
