# Generated by Django 6.1.1 on 2026-10-04 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0010_job_posting_interpretation_decisions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingDescriptorProjection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(editable=False)),
                ('revision', models.PositiveBigIntegerField()),
                ('snapshot', models.JSONField()),
                ('expected_descriptor_digest', models.CharField(max_length=64)),
                ('method', models.CharField(default='explicit_owner', editable=False, max_length=32)),
                ('projection_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_posting_descriptor_projections', to=settings.AUTH_USER_MODEL)),
                ('arbitration_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descriptor_projections', to='postings.jobpostinginterpretationdecision')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descriptor_projections', to='postings.jobposting')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('posting', 'operation_id'), name='job_post_proj_operation'), models.UniqueConstraint(fields=('posting', 'revision'), name='job_post_proj_revision'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='job_post_proj_positive'), models.CheckConstraint(condition=models.Q(('method', 'explicit_owner')), name='job_post_proj_method'), models.CheckConstraint(condition=models.Q(('projection_version', 1)), name='job_post_proj_version')],
            },
        ),
    ]
