# Generated by Django 6.1.1 on 2026-10-04 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sync', '0007_gmail_mailbox_identity'),
        ('postings', '0011_job_posting_descriptor_projections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingAllocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation_id', models.UUIDField(editable=False)),
                ('method', models.CharField(default='explicit_owner', editable=False, max_length=32)),
                ('allocation_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_posting_allocations', to='email_sync.accountmailboxbinding')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_posting_allocations', to=settings.AUTH_USER_MODEL)),
                ('initial_source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job_posting_allocation', to='postings.postingsource')),
                ('interpretation_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_posting_allocations', to='postings.retainedpostinginterpretationdecision')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job_posting_allocation', to='postings.retainedpostingitem')),
                ('posting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='allocation', to='postings.jobposting')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('method', 'explicit_owner')), name='job_post_alloc_method'), models.CheckConstraint(condition=models.Q(('allocation_version', 1)), name='job_post_alloc_version')],
            },
        ),
    ]
