# Generated by Django 6.1.1 on 2026-09-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mail_app', 'Mail.app'), ('gmail', 'Gmail (legacy)'), ('outlook', 'Outlook (legacy)'), ('icloud', 'iCloud (legacy)'), ('imap', 'IMAP (legacy)')], default='mail_app', max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('blocked', 'Blocked'), ('disconnected', 'Disconnected')], default='connected', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('matched_email_count', models.PositiveIntegerField(default=0)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='JobPostingSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posting_senders', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=512)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_identifiers', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=512)),
                ('subject', models.CharField(blank=True, max_length=998, null=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('guessed_company', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_kind', models.CharField(choices=[('unmatched', 'Unmatched'), ('ambiguous', 'Ambiguous')], default='unmatched', max_length=16)),
                ('kind', models.CharField(choices=[('application', 'Application'), ('posting', 'Posting')], default='application', max_length=16)),
                ('posting_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('posting_urls', models.JSONField(blank=True, default=list)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='email_sync.emailaccount')),
                ('candidate_applications', models.ManyToManyField(blank=True, related_name='candidate_discoveries', to='applications.application')),
            ],
            options={
                'verbose_name_plural': 'discoveries',
            },
        ),
        migrations.CreateModel(
            name='AccountMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=512)),
                ('subject', models.CharField(blank=True, max_length=998, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='email_sync.emailaccount')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_matches', to='applications.application')),
            ],
        ),
        migrations.AddConstraint(
            model_name='jobpostingsender',
            constraint=models.UniqueConstraint(fields=('workspace', 'sender'), name='unique_job_posting_sender_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='threadidentifier',
            constraint=models.UniqueConstraint(fields=('application', 'message_id'), name='unique_thread_identifier'),
        ),
        migrations.AddIndex(
            model_name='discovery',
            index=models.Index(fields=['status'], name='email_sync_disc_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='discovery',
            constraint=models.UniqueConstraint(fields=('account', 'message_id'), name='unique_discovery_message'),
        ),
        migrations.AddIndex(
            model_name='accountmatch',
            index=models.Index(fields=['application'], name='email_sync_match_app_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountmatch',
            constraint=models.UniqueConstraint(fields=('account', 'message_id'), name='unique_account_match_message'),
        ),
    ]
