# Generated by Django 6.1.1 on 2026-09-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmatch',
            options={'verbose_name_plural': 'account matches'},
        ),
    ]
