# Generated by Django 6.1.1 on 2026-09-20 03:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('email_sync', '0005_imapcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portable_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('provider', models.CharField(max_length=16)),
                ('evidence', models.JSONField()),
                ('established_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='RetainedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portable_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('provider', models.CharField(max_length=16)),
                ('locator_kind', models.CharField(max_length=32)),
                ('locator_value', models.CharField(max_length=512)),
                ('folder', models.CharField(blank=True, max_length=512)),
                ('stability', models.CharField(max_length=128)),
                ('representation_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('content', models.JSONField()),
                ('content_digest', models.CharField(max_length=64)),
                ('has_conflict', models.BooleanField(default=False, editable=False)),
                ('retained_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='email_sync.mailboxlineage')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='RetentionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('initial_digest', models.CharField(max_length=64)),
                ('has_conflict', models.BooleanField(default=False, editable=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='RetainedObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('state', models.CharField(choices=[('retained', 'Retained'), ('unresolved', 'Unresolved'), ('conflict', 'Conflict')], max_length=16)),
                ('conflict_reason', models.CharField(blank=True, max_length=32)),
                ('observed_at', models.DateTimeField()),
                ('retained_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='email_sync.mailboxlineage')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='email_sync.retainedmessage')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.workspace')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='email_sync.retentionkey')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mailboxlineage',
            constraint=models.UniqueConstraint(fields=('workspace', 'portable_id'), name='retained_mailbox_portable'),
        ),
        migrations.AddConstraint(
            model_name='retainedmessage',
            constraint=models.UniqueConstraint(fields=('workspace', 'portable_id'), name='retained_message_portable'),
        ),
        migrations.AddConstraint(
            model_name='retainedmessage',
            constraint=models.UniqueConstraint(fields=('workspace', 'mailbox', 'provider', 'locator_kind', 'locator_value', 'folder', 'stability'), name='retained_source_namespace'),
        ),
        migrations.AddConstraint(
            model_name='retentionkey',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='retained_observation_key'),
        ),
        migrations.AddConstraint(
            model_name='retainedobservation',
            constraint=models.UniqueConstraint(fields=('key', 'digest'), name='retained_observation_variant'),
        ),
    ]
