# Generated by Django 6.1.1 on 2026-09-20 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('email_sync', '0006_retained_email_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMailboxBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_binding', to='email_sync.emailaccount')),
                ('mailbox', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account_binding', to='email_sync.mailboxlineage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MailboxPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=16)),
                ('namespace', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='principal', to='email_sync.mailboxlineage')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'provider', 'namespace', 'value'), name='mailbox_verified_principal')],
            },
        ),
    ]
