# Generated by Django 6.1.1 on 2026-09-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('applications', 'Applications'), ('credentials', 'Credentials'), ('network', 'Network'), ('resume_library', 'Resume library'), ('leads', 'Leads'), ('personal', 'Personal'), ('compliance', 'Compliance'), ('misc', 'Misc')], max_length=32)),
                ('company', models.CharField(max_length=255)),
                ('role_label', models.CharField(max_length=255)),
                ('source_relpath', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interviewing', 'Interviewing'), ('rejected', 'Rejected'), ('drafted', 'Drafted'), ('unknown', 'Unknown'), ('n/a', 'N/A')], default='unknown', max_length=16)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('first_activity', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('canonical', models.CharField(max_length=255)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_aliases', to='accounts.workspace')),
            ],
            options={
                'verbose_name_plural': 'company aliases',
            },
        ),
        migrations.CreateModel(
            name='Override',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='override', serialize=False, to='applications.application')),
                ('manual_status', models.CharField(blank=True, max_length=16, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('date_applied_source', models.CharField(blank=True, choices=[('confirmation', 'Confirmation'), ('posting', 'Posting')], max_length=16, null=True)),
                ('next_action', models.CharField(blank=True, max_length=255, null=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('activity_override', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16)),
                ('changed_at', models.DateTimeField()),
                ('source', models.CharField(default='manual', max_length=32)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
            ],
            options={
                'verbose_name_plural': 'status histories',
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['workspace', 'section'], name='app_workspace_section_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('workspace', 'section', 'company', 'role_label', 'source_relpath'), name='unique_application_identity_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='companyalias',
            constraint=models.UniqueConstraint(fields=('workspace', 'alias'), name='unique_company_alias_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='statushistory',
            index=models.Index(fields=['application', 'changed_at'], name='applications_app_changed_idx'),
        ),
    ]
