# Generated by Django 6.1.1 on 2026-09-13 11:57

import uuid
from django.db import migrations, models


def backfill_portable_ids(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    rows = Application.objects.using(schema_editor.connection.alias)
    for pk in rows.filter(portable_id__isnull=True).values_list("pk", flat=True).iterator():
        rows.filter(pk=pk, portable_id__isnull=True).update(portable_id=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='portable_id',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(backfill_portable_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='application', name='portable_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='source_relpath',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('workspace', 'portable_id'), name='unique_application_portable_id_per_workspace'),
        ),
    ]
