# Generated by Django 6.1.1 on 2026-09-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_allow_repeated_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category_revision',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
