# Generated by Django 6.1.1 on 2026-09-19 22:17

from django.db import migrations, models


def preserve_ambiguous_dates(apps, schema_editor):
    Override = apps.get_model("applications", "Override")
    Override.objects.using(schema_editor.connection.alias).filter(date_applied__isnull=False).update(
        date_applied_mode="legacy_preserved")


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_retained_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='activity_provenance',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='application',
            name='automatic_date_applied',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='date_candidate',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='application',
            name='derivation_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='application',
            name='derivation_state',
            field=models.CharField(choices=[('pending', 'pending'), ('current', 'current'), ('incomplete', 'incomplete'), ('needs_reconciliation', 'needs_reconciliation')], default='pending', editable=False, max_length=24),
        ),
        migrations.AddField(
            model_name='application',
            name='derivation_version',
            field=models.CharField(blank=True, editable=False, max_length=16),
        ),
        migrations.AddField(
            model_name='application',
            name='derived_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='first_activity_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='last_activity_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='override',
            name='date_applied_mode',
            field=models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual'), ('legacy_preserved', 'legacy_preserved'), ('suppressed', 'suppressed')], default='automatic', max_length=24),
        ),
        migrations.RunPython(preserve_ambiguous_dates, migrations.RunPython.noop),
        migrations.AddConstraint(model_name="application", constraint=models.CheckConstraint(
            condition=models.Q(first_activity__isnull=True) | models.Q(first_activity_date__isnull=True),
            name="application_first_one_precision")),
        migrations.AddConstraint(model_name="application", constraint=models.CheckConstraint(
            condition=models.Q(last_activity__isnull=True) | models.Q(last_activity_date__isnull=True),
            name="application_last_one_precision")),
    ]
