# Generated by Django 6.1.1 on 2026-09-20 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_deterministic_derivation'),
        ('applications', '0006_deterministic_derivation'),
        ('email_sync', '0006_retained_email_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portable_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('origin', models.CharField(choices=[('manual', 'Explicit manual attachment')], default='manual', editable=False, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_relationships', to='applications.application')),
                ('retained_message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_relationships', to='email_sync.retainedmessage')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('application', 'retained_message'), name='application_message_pair'), models.UniqueConstraint(fields=('workspace', 'portable_id'), name='application_message_portable'), models.CheckConstraint(condition=models.Q(('origin', 'manual')), name='application_message_origin')],
            },
        ),
    ]
