# Generated by Django 6.1.1 on 2026-09-26 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_deterministic_derivation'),
        ('applications', '0007_application_message'),
        ('email_sync', '0006_retained_email_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetainedApplicationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portable_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('initial_classification', models.CharField(choices=[('match', 'Single candidate'), ('ambiguous', 'Multiple candidates'), ('application', 'No candidate')], editable=False, max_length=16)),
                ('snapshot_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('originating_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='email_sync.retainedobservation')),
                ('retained_message', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='application_review', to='email_sync.retainedmessage')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='RetainedApplicationReviewCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_portable_id', models.UUIDField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retained_review_candidates', to='applications.application')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='applications.retainedapplicationreview')),
            ],
        ),
        migrations.AddConstraint(
            model_name='retainedapplicationreview',
            constraint=models.UniqueConstraint(fields=('workspace', 'portable_id'), name='application_review_portable'),
        ),
        migrations.AddConstraint(
            model_name='retainedapplicationreview',
            constraint=models.CheckConstraint(condition=models.Q(('initial_classification__in', ['match', 'ambiguous', 'application'])), name='application_review_class'),
        ),
        migrations.AddConstraint(
            model_name='retainedapplicationreviewcandidate',
            constraint=models.UniqueConstraint(fields=('review', 'application_portable_id'), name='application_review_candidate'),
        ),
    ]
