# Generated by Django 6.1.1 on 2026-09-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relpath', models.CharField(max_length=1024)),
                ('doc_type_override', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_overrides', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(max_length=64)),
                ('extractor_version', models.CharField(max_length=32)),
                ('extracted_json', models.JSONField()),
                ('extracted_at', models.DateTimeField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_extractions', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='FolderOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=1024)),
                ('section', models.CharField(max_length=32)),
                ('archived', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_overrides', to='accounts.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='documentoverride',
            constraint=models.UniqueConstraint(fields=('workspace', 'relpath'), name='unique_document_override_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='documentextraction',
            constraint=models.UniqueConstraint(fields=('workspace', 'content_hash'), name='unique_extraction_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='folderoverride',
            constraint=models.UniqueConstraint(fields=('workspace', 'folder'), name='unique_folder_override_per_workspace'),
        ),
    ]
