# Generated by Django 6.1.1 on 2026-09-13 21:57

import django.db.models.deletion
import documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0004_application_category_revision'),
        ('documents', '0002_document_and_fk_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portable_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255, validators=[documents.models.validate_category_name])),
                ('section', models.CharField(choices=[('credentials', 'credentials'), ('network', 'network'), ('resume_library', 'resume_library'), ('leads', 'leads'), ('compliance', 'compliance'), ('personal', 'personal'), ('misc', 'misc')], max_length=32)),
                ('archived', models.BooleanField(default=False)),
                ('revision', models.PositiveBigIntegerField(default=0, editable=False)),
                ('provenance', models.JSONField(default=dict, editable=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMembership',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='category_membership', serialize=False, to='applications.application')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='documents.category')),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('workspace', 'portable_id'), name='unique_category_portable_per_ws'),
        ),
    ]
