# Generated by Django 6.1.1 on 2026-09-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_deterministic_derivation'),
        ('applications', '0006_deterministic_derivation'),
        ('documents', '0005_retained_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='evidence_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='evidence_event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='evidence_event_provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='original_upload_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='verified_legacy_mtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_event_at__isnull', True), ('evidence_event_date__isnull', True), _connector='OR'), name='document_event_one_precision'),
        ),
    ]
