"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# base.py now lives in config/settings/, so BASE_DIR needs one more
# parent than the django-admin default to still point at backend/.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-01w5j4n_$-8om)s!@rpf!@(j^!(q4@!xy6%&b(()$l@89%faj#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'applications',
    'email_sync',
    'postings',
    'documents',
    'core',
]

# Must be set before the first makemigrations — swapping the user
# model later, once data/migrations exist against auth.User, is
# painful. See docs/DJANGO_MIGRATION_PLAN.md Phase 2.
AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# File storage (uploaded Documents: resumes, cover letters, evidence
# PDFs -- see docs/DJANGO_MIGRATION_PLAN.md Phase 4).
#
# base.py sets the plain-filesystem default so every environment has
# *something* that works out of the box; dev.py leaves it alone and
# just points MEDIA_ROOT/MEDIA_URL somewhere sane for local testing.
# prod.py is the one that actually overrides STORAGES["default"] to
# the S3 backend -- see that file for the real config. Local
# filesystem storage on a prod-style host would silently lose every
# uploaded file on the next deploy, so this default is dev-only in
# practice even though nothing here enforces that.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}


# Django REST Framework (docs/DJANGO_MIGRATION_PLAN.md Phase 8).
#
# SessionAuthentication over token auth: the `desktop/` launcher runs
# the frontend same-origin against this same server (see Phase 2's
# "decided based on whether the frontend stays same-origin" note), so
# there's no cross-origin case to design a token scheme around.
# BasicAuthentication is included only so DRF's browsable API and
# manual curl/http testing can authenticate without a browser session.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Gmail OAuth (Phase 9 slice, docs/DJANGO_MIGRATION_PLAN.md) --
# credentials for *this app's* registration with Google, not any
# user's mailbox credentials (those are the whole point of the OAuth
# dance and are never configured here). Real values must come from
# the environment in any deployed environment -- the empty-string
# defaults below only let local `manage.py test`/`runserver` boot
# without a real Google Cloud project configured; email_sync.oauth
# raises a clear error at the moment a connect flow is actually
# attempted with these unset, rather than failing silently.
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', '')
GOOGLE_OAUTH_REDIRECT_URI = os.environ.get(
    'GOOGLE_OAUTH_REDIRECT_URI', 'http://localhost:8000/api/email-accounts/gmail/callback'
)

# Symmetric key (cryptography.fernet) GmailCredential uses to encrypt
# stored OAuth access/refresh tokens at rest -- see email_sync.oauth's
# module docstring for why field-level encryption rather than relying
# on the database's own encryption-at-rest. SECURITY WARNING: this
# dev-only fallback key is checked into source control, same caveat as
# SECRET_KEY above -- generate a real one
# (`python -c "from cryptography.fernet import Fernet;
# print(Fernet.generate_key().decode())"`) and set
# GMAIL_TOKEN_ENCRYPTION_KEY in the environment before this is ever
# deployed. Rotating this key makes every already-stored token
# undecryptable, so treat it with the same care as a database
# password, not as a rotate-on-a-whim secret.
GMAIL_TOKEN_ENCRYPTION_KEY = os.environ.get(
    'GMAIL_TOKEN_ENCRYPTION_KEY', 'fXjaJnCzcqV7qdtv8krT14nLUD6QBFScd6jZf5hzVGg='
)

# Read-only scope only -- this app never sends, deletes, or modifies
# mail, only classifies it for matching (email_sync.matching), so the
# OAuth consent screen a user sees should never ask for more than
# reading.
GMAIL_OAUTH_SCOPES = ['https://www.googleapis.com/auth/gmail.readonly']

# Microsoft OAuth / Graph (Phase 9 second-provider slice,
# docs/DJANGO_MIGRATION_PLAN.md) -- this app's own Azure AD app
# registration credentials, not any user's mailbox credentials, same
# split as GOOGLE_OAUTH_CLIENT_ID/SECRET above. Real values must come
# from the environment in any deployed environment; the empty-string
# defaults below only let local manage.py test/runserver boot without
# a real Azure AD app registration configured -- email_sync.
# outlook_oauth raises a clear error at the moment a connect flow is
# actually attempted with these unset, rather than failing silently.
MICROSOFT_OAUTH_CLIENT_ID = os.environ.get('MICROSOFT_OAUTH_CLIENT_ID', '')
MICROSOFT_OAUTH_CLIENT_SECRET = os.environ.get('MICROSOFT_OAUTH_CLIENT_SECRET', '')
MICROSOFT_OAUTH_REDIRECT_URI = os.environ.get(
    'MICROSOFT_OAUTH_REDIRECT_URI', 'http://localhost:8000/api/email-accounts/outlook/callback'
)

# Symmetric key (cryptography.fernet) OutlookCredential uses to
# encrypt stored OAuth access/refresh tokens at rest -- deliberately a
# *separate* key from GMAIL_TOKEN_ENCRYPTION_KEY (see email_sync.
# outlook_oauth's module docstring for why). SECURITY WARNING: this
# dev-only fallback key is checked into source control, same caveat as
# GMAIL_TOKEN_ENCRYPTION_KEY above -- generate a real one the same way
# (`python -c "from cryptography.fernet import Fernet;
# print(Fernet.generate_key().decode())"`) and set
# MICROSOFT_TOKEN_ENCRYPTION_KEY in the environment before this is
# ever deployed. Rotating this key makes every already-stored Outlook
# token undecryptable, same caveat as the Gmail key.
MICROSOFT_TOKEN_ENCRYPTION_KEY = os.environ.get(
    'MICROSOFT_TOKEN_ENCRYPTION_KEY', 'Pkn_45gin4M7zHTs1htox81DGuwAV7ADpMKtZpQqd-4='
)

# Symmetric key (cryptography.fernet) IMAPCredential uses to encrypt
# the stored app password at rest -- deliberately a *separate* key
# from GMAIL_TOKEN_ENCRYPTION_KEY/MICROSOFT_TOKEN_ENCRYPTION_KEY (see
# email_sync.imap_auth's module docstring for why). SECURITY WARNING:
# this dev-only fallback key is checked into source control, same
# caveat as the other two encryption keys above -- generate a real one
# the same way (`python -c "from cryptography.fernet import Fernet;
# print(Fernet.generate_key().decode())"`) and set
# IMAP_TOKEN_ENCRYPTION_KEY in the environment before this is ever
# deployed. Rotating this key makes every already-stored IMAP password
# undecryptable, same caveat as the other two keys.
IMAP_TOKEN_ENCRYPTION_KEY = os.environ.get(
    'IMAP_TOKEN_ENCRYPTION_KEY', 'FKMi8JI8yo6UB7lC3PoLor_kuv2SAWF5l_rrD0WsoiA='
)


# Celery / background task scheduling (Phase 10 -- closes the "no
# background task runner" gap docs/DJANGO_MIGRATION_PLAN.md's Phase 9
# Known gaps and docs/DJANGO_BACKEND_HANDOFF.md §4 both flag). See
# config/celery.py for the Celery app itself and email_sync/tasks.py
# for what actually runs on this schedule.
#
# Redis is used as both broker and result backend -- one fewer moving
# part than a second Postgres-backed result store, and nothing in
# this app queries a task's result after the fact yet (the manual
# sync-now endpoint already returns SyncResult synchronously in its
# own request/response cycle; every Celery path here is fire-and-
# forget from the caller's side). Real deployments should set
# CELERY_BROKER_URL/CELERY_RESULT_BACKEND from the environment same as
# every other credential/connection setting above; the localhost
# default only lets local dev point at a `redis-server` running on
# its default port with zero extra config.
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Runs a task inline, synchronously, with no broker/worker process at
# all when true -- this sandbox (and possibly the user's own machine,
# until a real `redis-server` is running) has no broker available, so
# this is what lets `manage.py test`/`manage.py runserver` still work
# without one. Tests that need to exercise real `.delay()` dispatch
# (email_sync/tests/test_email_account_sync_all_view.py,
# test_tasks.py's sync_all_accounts_task tests) still explicitly patch
# the `.delay` call rather than relying on this flag, so it's safe to
# leave at its real-deployment default (False) here and only flip it
# via the environment for a throwaway local run.
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'False') == 'True'
CELERY_TASK_EAGER_PROPAGATES = True

# A plain number here is seconds (equivalent to
# `datetime.timedelta(seconds=900)`) rather than a `celery.schedules.
# crontab(...)` instance deliberately -- it keeps this settings module
# free of any top-level `import celery`, consistent with base.py not
# importing any other third-party package's code at module level
# either (every other integration above is env-var-only until the
# moment a real connect flow needs the actual client library). Wanting
# a calendar-aligned schedule instead of a fixed interval is a one-line
# change to `from celery.schedules import crontab` plus this value the
# day that's actually needed.
CELERY_BEAT_SCHEDULE = {
    'sync-all-connected-email-accounts': {
        'task': 'email_sync.tasks.sync_all_accounts_task',
        'schedule': 900.0,  # every 15 minutes
    },
}
