# Generated by Django 6.1.1 on 2026-09-13 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0002_application_portable_identity'),
        ('core', '0002_alter_hubsettings_role_location_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRequestIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('digest', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=16)),
                ('completed', models.BooleanField(default=False)),
                ('result_portable_id', models.UUIDField(null=True)),
                ('challenge_token', models.CharField(blank=True, max_length=64)),
                ('challenge_revision', models.CharField(blank=True, max_length=64)),
                ('challenge_expires_at', models.DateTimeField(null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.application')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor', 'workspace', 'key'), name='unique_application_request_key')],
            },
        ),
    ]
