# Generated by Django 6.1.1 on 2026-09-13 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_applicationrequestintent'),
        ('documents', '0003_category_categorymembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrequestintent',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.category'),
        ),
    ]
